#!/bin/sh
NUM_FAILURES=0

../../check.template markov -p arb -ghybrid $@
NUM_FAILURES=$(($NUM_FAILURES+$?))

../../check.template markov -p arb -gproject-and-lift $@
NUM_FAILURES=$(($NUM_FAILURES+$?))

# The script returns the number of failures encountered.
exit $NUM_FAILURES
