language: cpp

services:
 - docker

sudo: false

env:
 - DOCKER=i386/ubuntu
 - 

matrix:
  include:
    - os: osx
      env:
       -
      before_script:
       - brew update
       - brew install glpk

addons:
  apt_packages:
      - libgmp-dev
      - autoconf
      - automake
      - libtool
      - libglpk-dev

script: ./.travis-build.sh
