language: cpp

sudo: false

matrix:
  include:
    - services:
      - docker
      env:
      - DOCKER=i386/ubuntu
  include:
    - os: linux
      env:
       -
  include:
    - os: osx
      env:
       -
      before_script:
       - brew update
       - brew install glpk

addons:
  apt_packages:
      - libgmp-dev
      - autoconf
      - automake
      - libtool
      - libglpk-dev

script: ./.travis-build.sh
