#!/bin/sh
NUM_FAILURES=0

../check.template groebner -afifo
NUM_FAILURES=$(($NUM_FAILURES+$?))

../check.template groebner -aweighted
NUM_FAILURES=$(($NUM_FAILURES+$?))

# The script returns the number of failures encountered.
exit $NUM_FAILURES
