#!/bin/sh
NUM_FAILURES=0

../check.template qsolve -m -o maxcutoff $@
NUM_FAILURES=$(($NUM_FAILURES+$?))

../check.template qsolve -s -o maxinter $@
NUM_FAILURES=$(($NUM_FAILURES+$?))

# The script returns the number of failures encountered.
exit $NUM_FAILURES
