#!/bin/sh
NUM_FAILURES=0

../check.template markov -ghybrid $@
NUM_FAILURES=$(($NUM_FAILURES+$?))

../check.template markov -gproject-and-lift $@
NUM_FAILURES=$(($NUM_FAILURES+$?))

# The script returns the number of failures encountered.
exit $NUM_FAILURES
